### ISSUE TITLE
Beef up your README

### ISSUE THREAD

**Issue by liorkesos** [alonoz/Smth#2]
Seems you have a dependency for a python library.
Please update how to deliver the requirement 
</dont-make-me-think>

**Comment by alonoz** [comment]
added the profile, you need git version of w3af running (git clone --depth
1 https://github.com/andresriancho/w3af.git)

**Comment by alonoz** [comment]
added some README lines

**Comment by alonoz** [comment]
Added zaproxy python dependency in README, per request.
